-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-10-18 13:41:16 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE clients (
    client_id   INTEGER NOT NULL,
    first_name  VARCHAR2(16),
    middle_name VARCHAR2(16),
    last_name   VARCHAR2(32),
    phone       VARCHAR2(16),
    email       VARCHAR2(255)
);

ALTER TABLE clients ADD CONSTRAINT clients_pk PRIMARY KEY ( client_id );

CREATE TABLE employees (
    empl_id     INTEGER NOT NULL,
    first_name  VARCHAR2(16),
    middle_name VARCHAR2(16),
    last_name   VARCHAR2(32),
    phone       VARCHAR2(16),
    pos_id      INTEGER NOT NULL
);

ALTER TABLE employees ADD CONSTRAINT employees_pk PRIMARY KEY ( empl_id );

CREATE TABLE genres (
    genre_id   INTEGER NOT NULL,
    genre_name VARCHAR2(32)
);

ALTER TABLE genres ADD CONSTRAINT genres_pk PRIMARY KEY ( genre_id );

CREATE TABLE positions (
    pos_id   INTEGER NOT NULL,
    pos_name VARCHAR2(24)
);

ALTER TABLE positions ADD CONSTRAINT possitions_pk PRIMARY KEY ( pos_id );

CREATE TABLE products (
    prod_id         INTEGER NOT NULL,
    type_id         INTEGER NOT NULL,
    year_of_release INTEGER,
    prod_name       VARCHAR2(64),
    artist          VARCHAR2(64),
    genre_id        INTEGER NOT NULL,
    label           VARCHAR2(64),
    price           FLOAT(6),
    av_quantity     INTEGER
);

ALTER TABLE products ADD CONSTRAINT products_pk PRIMARY KEY ( prod_id );

CREATE TABLE sales (
    sale_id   INTEGER NOT NULL,
    client_id INTEGER NOT NULL,
    empl_id   INTEGER NOT NULL,
    sale_date DATE
);

ALTER TABLE sales ADD CONSTRAINT sales_pk PRIMARY KEY ( sale_id );

CREATE TABLE sales_products (
    sale_id       INTEGER NOT NULL,
    prod_id       INTEGER NOT NULL,
    sale_quantity INTEGER
);

CREATE TABLE types (
    type_id   INTEGER NOT NULL,
    type_name VARCHAR2(32)
);

ALTER TABLE types ADD CONSTRAINT product_types_pk PRIMARY KEY ( type_id );

ALTER TABLE employees
    ADD CONSTRAINT employees_possitions_fk FOREIGN KEY ( pos_id )
        REFERENCES positions ( pos_id );

ALTER TABLE products
    ADD CONSTRAINT products_genres_fk FOREIGN KEY ( genre_id )
        REFERENCES genres ( genre_id );

ALTER TABLE products
    ADD CONSTRAINT products_types_fk FOREIGN KEY ( type_id )
        REFERENCES types ( type_id );

ALTER TABLE sales
    ADD CONSTRAINT sales_clients_fk FOREIGN KEY ( client_id )
        REFERENCES clients ( client_id );

ALTER TABLE sales
    ADD CONSTRAINT sales_employees_fk FOREIGN KEY ( empl_id )
        REFERENCES employees ( empl_id );

ALTER TABLE sales_products
    ADD CONSTRAINT sales_products_products_fk FOREIGN KEY ( prod_id )
        REFERENCES products ( prod_id );

ALTER TABLE sales_products
    ADD CONSTRAINT sales_products_sales_fk FOREIGN KEY ( sale_id )
        REFERENCES sales ( sale_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
