---user creation---
creat user CLIENT identified by client;
creat user EMPLOYEE identified by employee;
creat user ADMIN identified by admin;

---role creation---
creat ROLE clients;
create ROLE employees;
create ROLE admins; 


---granting priviliges to roles---

---admin---
GRANT SELECT, INSERT, DELETE, UPDATE ON ARTISTS TO admins;
GRANT SELECT, INSERT, DELETE, UPDATE ON CLIENTS TO admins;
GRANT SELECT, INSERT, DELETE, UPDATE ON EMPLOYEES TO admins;
GRANT SELECT, INSERT, DELETE, UPDATE ON GENRES TO admins;
GRANT SELECT, INSERT, DELETE, UPDATE ON LABELS TO admins;
GRANT SELECT, INSERT, DELETE, UPDATE ON POSITIONS TO admins;
GRANT SELECT, INSERT, DELETE, UPDATE ON PRODUCTS TO admins;
GRANT SELECT, INSERT, DELETE, UPDATE ON SALES TO admins;
GRANT SELECT, INSERT, DELETE, UPDATE ON SALES_PRODUCTS TO admins;
GRANT SELECT, INSERT, DELETE, UPDATE ON TYPES TO admins;

GRANT EXECUTE ON ART_INS TO admins;
GRANT EXECUTE ON ART_UPD TO admins;
GRANT EXECUTE ON CLI_INS TO admins;
GRANT EXECUTE ON CLI_UPD TO admins;
GRANT EXECUTE ON EMP_INS TO admins;
GRANT EXECUTE ON EMP_UPD TO admins;
GRANT EXECUTE ON LAB_INS TO admins;
GRANT EXECUTE ON LAB_UPD TO admins;
GRANT EXECUTE ON PRO_INS TO admins;
GRANT EXECUTE ON PRO_UPD TO admins;
GRANT EXECUTE ON SAL_INS TO admins;
GRANT EXECUTE ON SAL_UPD TO admins;
GRANT EXECUTE ON SAL_PRO_INS TO admins;
GRANT EXECUTE ON SAL_PRO_UPD TO admins;
GRANT EXECUTE ON FIND_CLIENT_PRODUCTS TO admins;
GRANT EXECUTE ON FIND_EMPLOYEE_SALES TO admins;
GRANT EXECUTE ON FIND_LATEST_SALES TO admins;
GRANT EXECUTE ON FIND_SALE_PRODUCTS TO admins;
GRANT EXECUTE ON RETURN_SALE TO admins;

---clients---
GRANT SELECT ON ARTISTS TO clients;
GRANT SELECT ON GENRES TO clients;
GRANT SELECT ON LABELS TO clients;
GRANT SELECT ON PRODUCTS TO clients;
GRANT SELECT ON TYPES TO clients;

GRANT EXECUTE ON return_sale TO clients;

---employees---
GRANT SELECT ON ARTISTS TO employees;
GRANT SELECT ON CLIENTS TO employees;
GRANT SELECT ON EMPLOYEES TO employees;
GRANT SELECT ON GENRES TO employees;
GRANT SELECT ON LABELS TO employees;
GRANT SELECT ON POSITIONS TO employees;
GRANT SELECT ON PRODUCTS TO employees;
GRANT SELECT ON SALES TO employees;
GRANT SELECT ON SALES_PRODUCTS TO employees;
GRANT SELECT ON TYPES TO employees;

GRANT INSERT, UPDATE ON ARTISTS TO employees;
GRANT INSERT, UPDATE ON CLIENTS TO employees;
GRANT INSERT, UPDATE ON GENRES TO employees;
GRANT INSERT, UPDATE ON LABELS TO employees;
GRANT INSERT, UPDATE ON POSITIONS TO employees;
GRANT INSERT, UPDATE ON SALES TO employees;
GRANT INSERT, UPDATE ON SALES_PRODUCTS TO employees;
GRANT INSERT, UPDATE ON TYPES TO employees;

GRANT EXECUTE ON ART_INS TO employees;
GRANT EXECUTE ON CLI_INS TO employees;
GRANT EXECUTE ON EMP_INS TO employees;
GRANT EXECUTE ON LAB_INS TO employees;
GRANT EXECUTE ON PRO_INS TO employees;
GRANT EXECUTE ON SAL_INS TO employees;
GRANT EXECUTE ON SAL_PRO_INS TO employees;
GRANT EXECUTE ON FIND_CLIENT_PRODUCTS TO employees;
GRANT EXECUTE ON FIND_EMPLOYEE_SALES TO employees;
GRANT EXECUTE ON FIND_LATEST_SALES TO employees;
GRANT EXECUTE ON FIND_SALE_PRODUCTS TO employees;

---revoking priviliges from roles---

---clients---
REVOKE INSERT, DELETE, UPDATE ON ARTISTS FROM clients;
REVOKE INSERT, DELETE, UPDATE ON CLIENTS FROM clients;
REVOKE INSERT, DELETE, UPDATE ON EMPLOYEES FROM clients;
REVOKE INSERT, DELETE, UPDATE ON GENRES FROM clients;
REVOKE INSERT, DELETE, UPDATE ON LABELS FROM clients;
REVOKE INSERT, DELETE, UPDATE ON POSITIONS FROM clients;
REVOKE INSERT, DELETE, UPDATE ON PRODUCTS FROM clients;
REVOKE INSERT, DELETE, UPDATE ON SALES FROM clients;
REVOKE INSERT, DELETE, UPDATE ON SALES_PRODUCTS FROM clients;
REVOKE INSERT, DELETE, UPDATE ON TYPES FROM clients;

---employees---
REVOKE DELETE ON ARTISTS FROM employees;
REVOKE DELETE ON CLIENTS FROM employees;
REVOKE DELETE ON EMPLOYEES FROM employees;
REVOKE DELETE ON GENRES FROM employees;
REVOKE DELETE ON LABELS FROM employees;
REVOKE DELETE ON POSITIONS FROM employees;
REVOKE DELETE ON PRODUCTS FROM employees;
REVOKE DELETE ON SALES FROM employees;
REVOKE DELETE ON SALES_PRODUCTS FROM employees;
REVOKE DELETE ON TYPES FROM employees;

REVOKE EXECUTE ON RETURN_SALE TO employees;

---granting roles to users---
grant admins to ADMIN;
grant employees to EMPLOYEE;
grant clients to CLIENT;